# Generated by Django 3.2 on 2021-06-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
