# Generated by Django 3.2 on 2021-06-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_tableno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tableno',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
