# Generated by Django 3.2 on 2021-06-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_tableno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='total',
            field=models.FloatField(blank=True),
        ),
    ]
