# Generated by Django 3.2 on 2021-06-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='total',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
