# Generated by Django 3.2 on 2021-06-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210622_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='adminnote',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='total',
        ),
    ]
